name: PYPI Prod Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write


jobs:
  enforce-main-only:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if not on main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "❌ This workflow can ONLY run on the main branch."
          echo "Current branch: ${{ github.ref }}"
          exit 1

      - name: Continue if main
        run: |
          echo "✔ Running workflow on main branch."

  lint:
    name: Ruff Lint Checks
    runs-on: ubuntu-latest
    needs: 
      - enforce-main-only

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff checks
        run: |
          ruff check .

  unit_test:
    name: Unit Tests in branch
    runs-on: ubuntu-latest
    needs: 
      - enforce-main-only

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage report (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: htmlcov  

  deploy_flag_check:
    name: Check Deploy Flag
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit_test

    outputs:
      deploy_enabled: ${{ steps.deploy_flag_check_.outputs.deploy_enabled }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run deploy flag check
        id: deploy_flag_check_
        run: |
          python scripts/check_deployment.py

  check_test_pypi:
    name: Check Test PyPI Version
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit_test
      - deploy_flag_check

    if: ${{ needs.deploy_flag_check.outputs.deploy_enabled == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install version checker dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging

      - name: Run version check
        run: python scripts/check_pypi_version.py --test --stage deployed

  check_prod_pypi:
    name: Check Prod PyPI Version
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit_test
      - deploy_flag_check

    if: ${{ needs.deploy_flag_check.outputs.deploy_enabled == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install version checker dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging

      - name: Run version check
        run: python scripts/check_pypi_version.py --prod --stage deploying

  manual_approval:
    name: Manual Approval Before Prod Deploy
    runs-on: ubuntu-latest
    needs: 
      - check_test_pypi
      - check_prod_pypi

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: AdamIH1
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1
          issue-title: "Approve Deployment to ProdPyPI"
          issue-body: "Approve deployment to ProdPyPI for this branch."

  publish_prod_pypi:
    name: Publish to Prod PyPI
    needs: [manual_approval]
    runs-on: ubuntu-latest
    environment: pypi_prod

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build Package
        run: python -m build

      - name: Publish to Prod PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
